# 
name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    
      - name: Notify Slack on Success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          text: "SonarQube Quality Gate PASSED for ${{ github.repository }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      
      - name: Notify Slack on Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: "SonarQube Quality Gate FAILED for ${{ github.repository }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          

      - name: Setup Snyk
        uses: snyk/actions/node@master
      - name: Run Snyk Scan
        id: snyk-test
        continue-on-error: true
        run: snyk test backend/
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      
      - name: Notify Slack - Snyk Success
        if: steps.snyk-test.outcome == 'success'
        uses: 8398a7/action-slack@v3
        with:
          status: success
          text: "Snyk scan PASSED for ${{ github.repository }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      
      - name: Notify Slack - Snyk Failure
        if: steps.snyk-test.outcome == 'failure'
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: "Snyk scan FAILED (vulnerabilities found) in ${{ github.repository }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}